### ISSUE TITLE
Will be thankthul for 0.14.8 update

### ISSUE THREAD

**Issue by konopiux** [webjars/angular-ui-select#13]

**Comment by jamesward** [comment]
I don't see a tagged release for that version: https://github.com/angular-ui/ui-sortable/tags

**Comment by konopiux** [comment]
Why sortable?
I was asking about ui-select: https://github.com/angular-ui/ui-select/tags

On 21 February 2016 at 17:45, James Ward <notifications@github.com> wrote:

> I don't see a tagged release for that version:
> https://github.com/angular-ui/ui-sortable/tags
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/angular-ui-select/issues/13#issuecomment-186855891>
> .
>



-- 
Your sincerely,
Edgaras
-----------------------
+3144499157

**Comment by jamesward** [comment]
Whoops.  My bad.  I tab-completed into the wrong WebJar directory.

**Comment by konopiux** [comment]
Np. Thank you for responce :)


On 21 February 2016 at 18:04, James Ward <notifications@github.com> wrote:

> Whoops. My bad. I tab-completed into the wrong WebJar directory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webjars/angular-ui-select/issues/13#issuecomment-186859895>
> .
>



-- 
Your sincerely,
Edgaras
-----------------------
+3144499157
