### ISSUE TITLE
Version 0.18.0 contains 0.17.1

### ISSUE THREAD

**Issue by rvt** [webjars/angular-ui-select#15]
Hey Guys,

any reason why http://cdn.jsdelivr.net/webjars/org.webjars.bower/angular-ui-select/0.18.0/dist/select.min.js contains 0.17.1 ?

**Comment by jamesward** [comment]
That is what is in their git repo: https://github.com/angular-ui/ui-select/blob/v0.18.0/dist/select.min.js
